### ISSUE TITLE
Can't see pictures anymore & can't upgrade

### ISSUE THREAD

**Issue by oleole39** [YunoHost-Apps/cinny_ynh#72]
### Describe the bug

Can't see in-discussion media anymore since quite a while.
It shows a placeholder with a "Retry" button on it, and a "Failed to load image" pops up when pressing it. 
In the Network tab of the dev tools, I can see corresponding GET requests answered with 404 error.

I notice as well that Github has cinny_ynh 4.2.1\~ynh1 but that for some reason my instance does not show any update and is stuck to 3.2.0\~ynh2.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 12.0.4.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *4.2.1~ynh1*
- If upgrading, current package version: *3.2.0~ynh2*

**Comment by Salamandar** [comment]
Should be fixed now.

**Comment by oleole39** [comment]
Hmm indeed, I could update with `--force`, but now I can't open Cinny anymore.

**Comment by oleole39** [comment]
> EDIT : Ah, yeah, there is a reason why the package is "broken", but you can upgrade with

What is that reason ? Is the picture bug mentioned here or something else ?

**Comment by Salamandar** [comment]
No, the reason is https://github.com/YunoHost-Apps/cinny_ynh/pull/66 

They decided the prebuilt artifacts are for the domain root and can't be used on a subpath anymore `mydomain.tld/cinny`, and for that you need to configure BEFORE building the app.

Building the app takes multiple GB of RAM, so that's not applicable to most usages (small SBCs with a maximum of 4GB of RAM)… So I can't decide if I just remove the possibility to install on a subpath or if I exclude low-ram instances.

**Comment by oleole39** [comment]
Thanks, I answer on that topic on #66
